### ISSUE TITLE
Update to support Jellyfin 10.6.0

### ISSUE THREAD

**Issue by ElevonsJKeloids** [BobHasNoSoul/JFTool#2]
JFTool doesn't work with the latest jellyfin release!

**Comment by BobHasNoSoul** [comment]
working on it, they moved a lot of things to single line type but i will find a way to update the code to their new structure moving all of the structures when i can. so far i have gotten the image replacement working, title replacement working and image in the side bar working, trailer tab to requests working.. link addition is next big thing i'm attempting to port over but the change to single line has thrown me a bit with my free time i will be getting that hurdle out of the way

**Comment by C-Fu** [comment]
> i'm attempting to port over but the change to single line has thrown me a bit with my free time i will be getting that hurdle out of the way

Appreciate your time in doing this! Awesome dude

**Comment by BobHasNoSoul** [comment]
Thanks for the support C-Fu :)
I have a semi-working tool that will be released tomorrow, hopefully if not the day after (a few things i need to poke first like docker locations and calls) but it should do most of the features that this tool is known for, more will be added but it should serve as a decent bridge. The workaround I had to do was make a template for each and every choice and have static markers that get replaced with user keystrokes (for names urls etc) to make the code simpler instead of me trying to figure out a simple way to get gawk and sed to play nice with single line arguments that insert instead of replace (like the old tool) i will also be posting a css set that can be simply copied and pasted into the general tab that can be used to convert their dark to clear theme. that may take a little longer because i will need to update the read me file to demonstrate how that works.

here is a sneak peak
![10 6 jftool test](https://user-images.githubusercontent.com/23018412/88118962-ee41d680-cbb6-11ea-8222-71d0d3c0dd73.PNG)

**Comment by BobHasNoSoul** [comment]
beta 10.6.0 version released and has main core functionality it may have a few bugs but should function until i get a little bit more time to throw the rest of the features required into it.. if you find any issues or it doesnt work please let me know and will try to fix them. for now this issue will be closed :)
